// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4jVjDDTvQF73lWwTTvGVGRCP_DHctyF8',
    appId: '1:823030253297:web:fa64a7f3d1dee1d5464b50',
    messagingSenderId: '823030253297',
    projectId: 'trabalho-2-31a95',
    authDomain: 'trabalho-2-31a95.firebaseapp.com',
    storageBucket: 'trabalho-2-31a95.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLzk6XF_57stOAyuzhfu9HLXLSzDlGygA',
    appId: '1:823030253297:android:d25568399a64fe07464b50',
    messagingSenderId: '823030253297',
    projectId: 'trabalho-2-31a95',
    storageBucket: 'trabalho-2-31a95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4_MGHD0H-6S6AQrSbtmENbB9UCADmcoA',
    appId: '1:823030253297:ios:5b8ddfd96c1f4c6b464b50',
    messagingSenderId: '823030253297',
    projectId: 'trabalho-2-31a95',
    storageBucket: 'trabalho-2-31a95.appspot.com',
    androidClientId: '823030253297-d77adoh603rflkn21q15vj2pk59508m4.apps.googleusercontent.com',
    iosClientId: '823030253297-15a4tk641ka1tl6tiocbvpclv8ns6tmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProjectName',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4_MGHD0H-6S6AQrSbtmENbB9UCADmcoA',
    appId: '1:823030253297:ios:5b8ddfd96c1f4c6b464b50',
    messagingSenderId: '823030253297',
    projectId: 'trabalho-2-31a95',
    storageBucket: 'trabalho-2-31a95.appspot.com',
    androidClientId: '823030253297-d77adoh603rflkn21q15vj2pk59508m4.apps.googleusercontent.com',
    iosClientId: '823030253297-15a4tk641ka1tl6tiocbvpclv8ns6tmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProjectName',
  );
}
